# Run with:
# ansible-playbook SambaDirectories.yml

---
- name: Configure Samba Directories
  hosts: all
  tasks:

  - name: Put in ORIANS workgroup
    replace:
      path: /etc/samba/smb.conf
      regexp: 'workgroup = WORKGROUP'
      replace: 'workgroup = ORIANS'

  - name: Add AllWrite Share
    ansible.builtin.lineinfile:
      path: /etc/samba/smb.conf
      line: "{{ item.line }}"
    loop:
      - { line: '[allwrite]' }
      - { line: 'comment = Writeable area' }
      - { line: 'path = /mnt/external/allwrite' }
      - { line: 'guest ok = Yes' }
      - { line: 'read only = No' }

  - name: Start Samba service
    ansible.builtin.systemd:
      state: restarted
      name: smb
