version: "3"
services:
  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - /opt/resiliosync/config:/config
      - /opt/resiliosync/downloads:/downloads
      - /mnt/external/sync:/sync
    ports:
      - 8888:8888
      - 55555:55555
    restart: unless-stopped
